pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "sampleproject:latest"
        COMPOSE_FILE = "docker-compose.yml"
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/mkaganm/sampleproject.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker-compose build'
                }
            }
        }

        stage('Unit Test') {
            steps {
                script {
                    // Run unit tests
                    sh 'docker run --rm $DOCKER_IMAGE go test -v ./...'
                }
            }
        }

        stage('Deploy with Docker Compose') {
            steps {
                script {
                    // Stop any existing services
                    sh "docker-compose down"

                    // Start the services defined in the docker-compose.yml
                    sh "docker-compose up -d"
                }
            }
        }
    }
}
